// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZFkMazSv6MCQqfanpoQw-mu2aPTu3A0',
    appId: '1:106081562694:web:b1533d2405cd002d8a1a47',
    messagingSenderId: '106081562694',
    projectId: 'whacamole-6ebc7',
    authDomain: 'whacamole-6ebc7.firebaseapp.com',
    storageBucket: 'whacamole-6ebc7.appspot.com',
    measurementId: 'G-GQZ5Z5SLFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYspq2BY2C7ewzs48ScujYtmXf_MCT-dI',
    appId: '1:106081562694:android:9624d3fea14f09a08a1a47',
    messagingSenderId: '106081562694',
    projectId: 'whacamole-6ebc7',
    storageBucket: 'whacamole-6ebc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFKVA7A19XGv2-s4Eu7ThD0-hcU02Sus',
    appId: '1:106081562694:ios:df517ceecae2480a8a1a47',
    messagingSenderId: '106081562694',
    projectId: 'whacamole-6ebc7',
    storageBucket: 'whacamole-6ebc7.appspot.com',
    androidClientId: '106081562694-21u732ispp2182qrkm8739ig899kp6e3.apps.googleusercontent.com',
    iosClientId: '106081562694-cd6if80v0811q479icquq8sjah0i44cq.apps.googleusercontent.com',
    iosBundleId: 'com.wonderkid.wakeamole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFKVA7A19XGv2-s4Eu7ThD0-hcU02Sus',
    appId: '1:106081562694:ios:c77e7f266ed48e5d8a1a47',
    messagingSenderId: '106081562694',
    projectId: 'whacamole-6ebc7',
    storageBucket: 'whacamole-6ebc7.appspot.com',
    androidClientId: '106081562694-21u732ispp2182qrkm8739ig899kp6e3.apps.googleusercontent.com',
    iosClientId: '106081562694-apbtddd8tl7t1du3baa0hbtfm36iffqj.apps.googleusercontent.com',
    iosBundleId: 'com.wonderkid.whacamole',
  );
}
